### ISSUE TITLE
[Bug Report] download takes forever

### ISSUE THREAD

**Issue by Gweenteaneko** [dr-nyt/NovelScraper#29]
**Enter an appropriate Title above**

**Please complete the following information):**
 - Operating System [OS]:  win10 ver.1703
 - App Version: 1.0.0

**Describe the bug**
while downloading a novel the download progress is sometime stuck at some percentage and its stays there not able to move thus not able to download it. if a title has large data or chapters the chances of this occurring is high, one time Im able to download only a small one with 44 chaps in it and completely downloading it. somehow I reinstall the whole thing re-download again the 44 chaps novel and its stuck same as others.

**To Reproduce**

**Expected behavior**
when downloading files always expect sooner or later the progress will stop, sending request again will stimulate the download progress

**Screenshots**

**Comment by dr-nyt** [comment]
Could you tell me what novel you were trying to download and from which source.

**Comment by Gweenteaneko** [comment]
for now im trying to download (https://novelplanet.com/Novel/I-Alone-Level-Up) i also tried the others same problems occurs

**Comment by Gweenteaneko** [comment]
btw i only use novel-planet

**Comment by dr-nyt** [comment]
I tried downloading multiple big novels from NovelPlanet like `I Alone Level Up` and `Overgeared`. Both of them downloaded correctly. You could try doing the following:

- Check if your internet connection is stable by downloading something (from Steam maybe?)
- Run the app as administrative.
- Maybe the UI is just stuck and it's actually downloading. In that case, check your download folder.
- Inside the app, press `CTRL + SHIFT + i` and check if you see any errors.

**Comment by Gweenteaneko** [comment]
-as for my internet I think not a problem its fast
-run as administrative? same occurrence still stuck
-as for ui its not downloading I always monitor my internet usage via net limiter and its not pulling any data 
-error 
CustomErrorname: "RequestError"message: "Error: read ECONNRESET"error: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)cause: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)response: undefinedoptions: {jar: RequestJar, headers: {…}, cloudflareMaxTimeout: 30000, followAllRedirects: true, requester: ƒ, …}stack: "RequestError: Error: read ECONNRESET↵    at onRequestResponse (C:\Users\venz\AppData\Local\Programs\novelscraper\resources\app.asar\node_modules\cloudscraper\index.js:165:21)↵    at Request.<anonymous> (C:\Users\venz\AppData\Local\Programs\novelscraper\resources\app.asar\node_modules\cloudscraper\index.js:144:7)↵    at Object.onceWrapper (events.js:300:26)↵    at Request.emit (events.js:210:5)↵    at Request.onRequestError (C:\Users\venz\AppData\Local\Programs\novelscraper\resources\app.asar\node_modules\request\request.js:877:8)↵    at ClientRequest.emit (events.js:210:5)↵    at TLSSocket.socketErrorListener (_http_client.js:406:9)↵    at TLSSocket.emit (events.js:210:5)↵    at emitErrorNT (internal/streams/destroy.js:92:8)↵    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)↵    at processTicksAndRejections (internal/process/task_queues.js:80:21)"__proto__: RequestError

**Comment by dr-nyt** [comment]
The current fix for bypassing Cloudflare was only a temporary fix and some people have reported it failing when trying to use it multiple times. I have been considering moving to a more stable fix which will not require me to update it every few months. I will probably work on that after some time, but for now, we will have to wait for a solid patch.

You could also try restarting your computer and also restarting your router/modem (wait 10 secs) so you can get a new IP if you are not static. If that doesn't fix it then you will probably have to wait a bit longer.

**Comment by Gweenteaneko** [comment]
ill wait then. thx for the attention
btw do you some place to where i can see some related problems regarding Novel-Scraper like forum or something?

**Comment by dr-nyt** [comment]
I do have a discord server where it's considerably easy to talk and I make most of my announcements there: https://discord.gg/Wya4Dst

**Comment by dr-nyt** [comment]
Just checking are you still having this issue? The cloudscraper module became deprecated and I would probably have to find another way which might take a while since I finally landed an internship 🎉

**Comment by dr-nyt** [comment]
Since novelplanet has shut down and won't be supported anymore, this issue won't be fixed.
